"""Textos del sitio en espanol e ingles: (es, en).

Regla de redaccion: frases cortas, sin jerga en la vista principal. Los terminos
tecnicos (brecha del producto, inflacion implicita, tasa neutral) solo aparecen en los
paneles "Detalle tecnico" y siempre con su explicacion.
"""

T = {
    # --- marco
    "titulo_pagina": ("ColombiaMacro · ¿Cómo va la economía colombiana?", "ColombiaMacro · How is Colombia's economy doing?"),
    "meta_desc": ("Tablero abierto con datos oficiales del DANE y el Banco de la República, actualizado a diario.",
                  "Open dashboard with official DANE and Banco de la República data, updated daily."),
    "sub_marca": ("USB Cali · datos oficiales", "USB Cali · official data"),
    "otro_idioma": ("English", "Español"),
    "nav_crec": ("Crecimiento", "Growth"), "nav_precios": ("Precios", "Prices"), "nav_banco": ("Tasas", "Rates"),
    "nav_mercados": ("Tasa de cambio", "Exchange rate"), "nav_todos": ("Indicadores", "Indicators"),
    "kicker": ("Datos oficiales · se actualiza cada hora en días hábiles", "Official data · updated hourly on business days"),
    "datos_al": ("datos al", "data as of"),
    "generado": ("Actualizado el", "Updated on"),
    "h1": ("¿Cómo va la economía colombiana?", "How is Colombia's economy doing?"),
    "aviso_estados": ("Las etiquetas describen cada dato frente a reglas explícitas (meta de inflación, ritmo habitual de crecimiento). No son recomendaciones de inversión.",
                      "Labels describe each figure against explicit rules (inflation target, usual growth pace). They are not investment advice."),
    "horizonte": ("Ver los gráficos de los últimos", "Show charts for the last"),
    "h3": ("3 años", "3 years"), "h5": ("5 años", "5 years"), "h10": ("10 años", "10 years"), "htodo": ("Todo", "All"),
    "detalle_tecnico": ("Para entender mejor", "Learn more"),
    "fuente_pie": ("Fuente", "Source"), "metodo_pie": ("Metodología", "Methodology"),
    "aviso": ("Tablero académico con datos oficiales. No constituye recomendación de inversión.",
              "Academic dashboard built on official data. Not investment advice."),
    "pendiente": ("Pendiente de la primera descarga automática.", "Awaiting the first automated download."),

    # --- tarjetas
    "c_crec": ("Crecimiento", "Growth"), "c_inf": ("Inflación", "Inflation"), "c_tasa": ("Tasa del Banco", "Policy rate"),
    "c_empleo": ("Desempleo", "Unemployment"), "c_dolar": ("Dólar", "US dollar"), "c_bolsa": ("Bolsa (COLCAP)", "Stocks (COLCAP)"),
    "crec_detalle": ("PIB real, variación anual", "Real GDP, y/y"),
    "ritmo_normal_corto": ("Ritmo habitual", "Usual pace"),
    "inf_detalle": ("Variación anual de precios", "Annual change in prices"),
    "meta_corta": ("meta 3%", "target 3%"),
    "tasa_detalle": ("Tasa de interés de referencia", "Benchmark interest rate"),
    "empleo_detalle": ("Tasa de desempleo", "Unemployment rate"),
    "dolar_detalle": ("Pesos por dólar (TRM)", "Pesos per dollar (TRM)"),
    "bolsa_detalle": ("Índice de la Bolsa de Colombia", "Colombian stock index"),
    "hace_ano": ("Hace un año", "A year ago"), "en_un_ano": ("En un año", "Over a year"), "hoy": ("Hoy", "Today"),
    "ec_fuerte": ("Por encima de lo habitual", "Above usual pace"), "ec_normal": ("Ritmo normal", "Normal pace"),
    "ec_lento": ("Lento", "Slow"), "ec_contraccion": ("En contracción", "Contracting"),
    "ei_en_meta": ("En la meta", "On target"), "ei_baja": ("Bajo la meta", "Below target"),
    "ei_sobre_meta": ("Sobre la meta", "Above target"), "ei_alta": ("Alta", "High"),
    "ep_restrictiva": ("Alta: frena la economía", "High: slows the economy"), "ep_neutral": ("Neutral", "Neutral"),
    "ep_expansiva": ("Baja: estimula la economía", "Low: stimulates the economy"), "ep_None": ("—", "—"),
    "ep2_restrictiva": ("alto, que frena la economía para bajar la inflación", "high enough to slow the economy and bring inflation down"),
    "ep2_neutral": ("neutral, que ni frena ni estimula la economía", "neutral, neither slowing nor stimulating the economy"),
    "ep2_expansiva": ("bajo, que estimula la economía", "low, stimulating the economy"),
    "ep2_None": ("sin calificar", "not rated"),
    "el_mejora": ("Mejorando", "Improving"), "el_estable": ("Estable", "Stable"), "el_empeora": ("Empeorando", "Worsening"),
    "peso_fuerte": ("Peso más fuerte", "Stronger peso"), "peso_debil": ("Peso más débil", "Weaker peso"),
    "peso_estable": ("Estable", "Stable"),
    "sube": ("Al alza", "Rising"), "baja": ("A la baja", "Falling"), "estable": ("Estable", "Stable"),

    # --- seccion 1
    "q_crec": ("¿Está creciendo la economía?", "Is the economy growing?"),
    "resp_crec": ("La producción del país (PIB) creció {v}% en el año terminado en {q}. En los últimos años, el ritmo habitual de crecimiento de Colombia ronda el {p}%.",
                  "Output (GDP) grew {v}% in the year to {q}. In recent years, Colombia's usual growth pace has been around {p}%."),
    "resp_ise": ("El indicador mensual de actividad del DANE (ISE), sin efectos de temporada, crecía {v}% anual en {f}.",
                 "DANE's seasonally adjusted monthly activity indicator (ISE) was growing {v}% y/y in {f}."),
    "g_crec": ("Crecimiento anual de la economía", "Annual economic growth"),
    "h_crec": ("Cada barra es un trimestre: cuánto creció la economía frente al mismo trimestre del año anterior. La línea punteada es el ritmo habitual; si las barras están por encima, la economía crece más rápido de lo normal.",
               "Each bar is a quarter: growth versus the same quarter a year earlier. The dotted line is the usual pace; bars above it mean faster-than-normal growth."),
    "pib_trim": ("PIB (trimestral)", "GDP (quarterly)"), "ise_mens": ("Actividad mensual (ISE)", "Monthly activity (ISE)"),
    "ritmo_normal": ("Ritmo habitual", "Usual pace"),
    "g_desempleo": ("Tasa de desempleo", "Unemployment rate"),
    "h_desempleo": ("Porcentaje de personas que buscan trabajo y no lo encuentran, sin efectos de temporada. La línea azul promedia tres meses para suavizar el ruido.",
                    "Share of people looking for work who cannot find it, seasonally adjusted. The blue line is a three-month average to smooth noise."),
    "td_mensual": ("Mensual", "Monthly"), "td_3m": ("Promedio de 3 meses", "3-month average"),
    "g_brecha": ("Producción frente a su capacidad (brecha del producto)", "Output vs capacity (output gap)"),
    "h_brecha": ("Por encima de cero la economía produce más que su capacidad sostenible, lo que presiona los precios; por debajo hay holgura. La franja muestra el rango entre tres métodos de estimación.",
                 "Above zero the economy produces more than its sustainable capacity, which pushes prices up; below zero there is slack. The band shows the range across three estimation methods."),
    "rango_metodos": ("Rango entre métodos", "Range across methods"), "brecha_principal": ("Estimación principal", "Main estimate"),
    "g_reloj": ("Reloj del ciclo: en qué fase estamos", "Cycle clock: which phase we are in"),
    "h_reloj": ("Cada punto es un trimestre (el grande, el más reciente). A la derecha, la economía produce por encima de su capacidad; arriba, esa diferencia está creciendo. Fase actual: {fase}.",
                "Each dot is a quarter (the large one is the latest). Right means output above capacity; up means that difference is growing. Current phase: {fase}."),
    "brecha_eje": ("Brecha", "Gap"), "direccion_eje": ("Cambio en 2 trimestres", "Change over 2 quarters"),
    "m_brecha": ("Método: la capacidad (PIB potencial) se estima con el filtro de Hodrick-Prescott aplicado solo con la información disponible en cada trimestre (λ = 1.600), y se contrasta con el mismo filtro sobre toda la muestra y con el método de Hamilton (2018). Los trimestres de la pandemia se excluyen al estimar la tendencia. Detalle completo en la metodología.",
                 "Method: capacity (potential GDP) is estimated with a Hodrick-Prescott filter using only the data available each quarter (λ = 1,600), cross-checked with the full-sample filter and Hamilton's (2018) method. Pandemic quarters are excluded when estimating the trend. Full detail in the methodology."),

    # --- seccion 2
    "q_precios": ("¿Cómo están los precios?", "What is happening to prices?"),
    "resp_precios": ("Los precios subieron {v}% en el último año (dato de {m}); hace un año la inflación era {a}%. La meta del Banco de la República es 3%, con un margen entre 2% y 4%.",
                     "Prices rose {v}% over the past year (data for {m}); a year ago inflation was {a}%. Banco de la República's target is 3%, with a 2%–4% range."),
    "resp_basica": ("Sin alimentos ni precios regulados, que son los más volátiles, la inflación es {v}%: la presión es general.",
                    "Excluding food and regulated prices, the most volatile items, inflation is {v}%: the pressure is broad-based."),
    "resp_espera": ("Los inversionistas esperan una inflación de {v}% para el próximo año.",
                    "Investors expect inflation of {v}% over the next year."),
    "g_inf": ("Inflación anual frente a la meta", "Annual inflation vs target"),
    "h_inf": ("La franja verde es el rango meta (2% a 4%). La línea naranja quita alimentos y precios regulados para mostrar la tendencia de fondo.",
              "The green band is the target range (2%–4%). The orange line removes food and regulated prices to show the underlying trend."),
    "inf_total": ("Inflación total", "Headline inflation"), "inf_fondo": ("Inflación de fondo", "Underlying inflation"),
    "inf_observada": ("Inflación observada", "Actual inflation"), "meta_label": ("Meta 3% (rango 2%–4%)", "Target 3% (2%–4% range)"),
    "g_espera": ("¿Qué inflación espera el mercado para el próximo año?", "What inflation does the market expect next year?"),
    "h_espera": ("Se calcula con los bonos del Gobierno (TES): la diferencia entre los que pagan una tasa fija y los que se ajustan por inflación. Si la línea morada está sobre la franja, el mercado cree que la inflación seguirá alta.",
                 "Computed from government bonds (TES): the gap between fixed-rate bonds and inflation-linked bonds. If the purple line is above the band, the market expects inflation to stay high."),
    "espera_1a": ("Esperada a 1 año", "Expected, 1 year"),
    "g_anclaje": ("Inflación esperada a largo plazo (años 5 a 10)", "Long-term expected inflation (years 5 to 10)"),
    "g_tray": ("La inflación que el mercado espera para los próximos 10 años", "The inflation the market expects over the next 10 years"),
    "h_tray": ("A la izquierda de la línea punteada, la inflación que ya ocurrió (gris). A la derecha, lo que hoy descuentan los bonos del Gobierno: {a}% en promedio el próximo año, {b}% por año entre el año 1 y el 5, y {c}% por año entre el año 5 y el 10 (esta última es la «5y5y»). La línea punteada gris es la misma lectura de hace un año: si la morada quedó por encima, el mercado ahora espera más inflación. Si los tramos bajan hacia la franja verde, el mercado cree que la inflación volverá a la meta.",
               "Left of the dotted line, inflation that already happened (grey). Right of it, what government bonds price today: {a}% on average next year, {b}% a year between years 1 and 5, and {c}% a year between years 5 and 10 (the latter is the \"5y5y\"). The dotted grey line is the same reading a year ago: if the purple one sits above it, the market now expects more inflation. If the steps fall toward the green band, the market believes inflation will return to target."),
    "tray_hoy": ("Lo que espera el mercado hoy ({f})", "Market expectation today ({f})"),
    "tray_antes": ("Lo que esperaba hace un año ({f})", "What it expected a year ago ({f})"),
    "tray_hoy_corto": ("hoy →", "today →"),
    "h_anclaje": ("No es un pronóstico de esta línea: cada punto es lo que el mercado esperaba, ese día, para la inflación promedio entre 5 y 10 años adelante (el dato de hoy se refiere a dentro de 5 a 10 años; la proyección completa está en el gráfico «La inflación que el mercado espera para los próximos 10 años»). Si se mantiene cerca de la meta, el mercado confía en que la inflación volverá al 3%; por encima de 4% se considera que las expectativas están desancladas.",
                  "This is not a forecast of this line: each point is what the market expected, on that day, for average inflation 5 to 10 years ahead (today's value refers to 5 to 10 years from now; the full projection is in the chart \"The inflation the market expects over the next 10 years\"). If it stays near target, the market trusts that inflation will return to 3%; above 4%, expectations are considered de-anchored."),
    "espera_largo": ("Esperada años 5–10 (5y5y)", "Expected years 5–10 (5y5y)"),
    "m_expect": ("Método: inflación implícita = (1 + tasa TES en pesos) / (1 + tasa TES en UVR) − 1, con curvas cero cupón de BanRep. Incluye primas por riesgo y liquidez, por lo que no es una expectativa pura.",
                 "Method: breakeven inflation = (1 + peso TES yield) / (1 + UVR TES yield) − 1, using BanRep zero-coupon curves. It includes risk and liquidity premia, so it is not a pure expectation."),

    # --- seccion 3
    "q_banco": ("¿Qué está haciendo el Banco de la República?", "What is Banco de la República doing?"),
    "resp_banco": ("La tasa de interés del Banco está en {v}%. Si a esa tasa se le resta la inflación que espera el mercado para el próximo año, queda la tasa real ex ante —lo que de verdad cuesta endeudarse—: {r}%, un nivel {e}.",
                   "The central bank's policy rate is {v}%. Subtracting the inflation the market expects for next year gives the ex-ante real rate —the true cost of borrowing—: {r}%, a level that is {e}."),
    "resp_banco_na": ("Pendiente de la primera descarga automática de la tasa de política.", "Awaiting the first automated download of the policy rate."),
    "g_politica": ("Tasa del Banco frente a la inflación", "Policy rate vs inflation"),
    "h_politica": ("Cuando la tasa del Banco (azul) está muy por encima de la inflación (naranja), el crédito es caro y la economía se enfría; así se busca bajar la inflación.",
                   "When the policy rate (blue) is well above inflation (orange), credit is expensive and the economy cools; that is how inflation is brought down."),
    "tpm_linea": ("Tasa del Banco de la República", "Policy rate"),
    "g_real": ("Tasa real frente a la tasa neutral", "Real rate vs neutral rate"),
    "h_real": ("Tasa real ex ante = tasa del Banco menos la inflación esperada para el próximo año (lo que de verdad cuesta endeudarse). La franja gris es la tasa neutral (2,7%–3,0%): por encima, la política frena la economía; por debajo, la estimula.",
               "Ex-ante real rate = policy rate minus the inflation expected for next year (the true cost of borrowing). The grey band is the neutral rate (2.7%–3.0%): above it, policy slows the economy; below it, it stimulates it."),
    "tasa_real": ("Tasa real ex ante", "Ex-ante real rate"), "neutral_label": ("Tasa neutral estimada 2,7%–3,0%", "Estimated neutral 2.7%–3.0%"),
    "g_curva": ("Tasas de los bonos del Gobierno por plazo (TES)", "Government bond yields by maturity (TES)"),
    "h_curva": ("Cuánto rinde prestarle al Gobierno a 1, 5 y 10 años, hoy y hace un año. Si toda la curva sube, el costo de financiarse aumenta para todos.",
                "What lending to the government pays at 1, 5 and 10 years, today and a year ago. When the whole curve rises, borrowing costs rise for everyone."),
    "hace_ano_c": ("Hace un año", "A year ago"),
    "plazo1": ("1 año", "1 year"), "plazo5": ("5 años", "5 years"), "plazo10": ("10 años", "10 years"),
    "m_politica": ("Método: tasa real ex ante = (1 + tasa del Banco) / (1 + inflación esperada a 1 año) − 1. La postura se califica como alta (restrictiva) si supera la tasa neutral estimada en más de 0,5 puntos.",
                   "Method: ex-ante real rate = (1 + policy rate) / (1 + 1-year expected inflation) − 1. The stance is called restrictive if it exceeds the estimated neutral rate by more than 0.5 points."),

    # --- seccion 4
    "q_mercados": ("¿Cómo está el peso frente al dólar?", "How is the peso doing against the dollar?"),
    "resp_dolar": ("Un dólar cuesta ${v} pesos ({c}% en un año).", "One dollar costs ${v} pesos ({c}% over a year)."),
    "resp_bolsa": ("La bolsa colombiana (COLCAP) varió {v}% en los últimos doce meses.", "The Colombian stock index (COLCAP) moved {v}% over the last twelve months."),
    "g_dolar": ("Pesos por dólar (TRM)", "Pesos per dollar (TRM)"),
    "h_dolar": ("Si la línea baja, el peso se fortalece: se necesitan menos pesos para comprar un dólar.",
                "When the line falls the peso strengthens: fewer pesos are needed to buy one dollar."),
    "trm_linea": ("Pesos por dólar", "Pesos per dollar"),
    "g_bolsa": ("Bolsa de Colombia (COLCAP)", "Colombian stock index (COLCAP)"),
    "h_bolsa": ("Índice que resume el precio de las acciones más negociadas en Colombia. No incluye dividendos.",
                "Index summarising the prices of the most traded Colombian stocks. Excludes dividends."),
    "colcap_linea": ("COLCAP", "COLCAP"),
    "g_itcr": ("Tasa de cambio real (2010 = 100)", "Real exchange rate (2010 = 100)"),
    "h_itcr": ("Compara precios de Colombia con los de sus socios comerciales en una misma moneda. Por debajo de 100 el peso está más fuerte que en 2010.",
               "Compares Colombian prices with those of trading partners in a common currency. Below 100 the peso is stronger than in 2010."),
    "itcr_linea": ("Tasa de cambio real", "Real exchange rate"),
    "m_mercados": ("Fuentes: TRM de la Superintendencia Financiera y COLCAP (BVC/MSCI) vía BanRep. El COLCAP cambió de metodología BVC a MSCI el 28 de mayo de 2021, con continuidad de niveles.",
                   "Sources: TRM from the Financial Superintendence and COLCAP (BVC/MSCI) via BanRep. COLCAP switched from BVC to MSCI methodology on 28 May 2021, keeping level continuity."),

    # --- seccion 5
    "q_externo": ("¿Cómo están las cuentas con el exterior y del Gobierno?", "How are external and government accounts?"),
    "resp_cc": ("El país gasta en el exterior más de lo que recibe: el déficit de cuenta corriente fue de {v}% del PIB en {f}.",
                "The country spends more abroad than it earns: the current-account deficit was {v}% of GDP in {f}."),
    "resp_deuda": ("La deuda del Gobierno Nacional Central llegó a {v}% del PIB en {f}.", "Central government debt reached {v}% of GDP in {f}."),
    "g_cc": ("Cuenta corriente (% del PIB)", "Current account (% of GDP)"),
    "h_cc": ("Barras negativas: déficit, es decir, el país depende de financiación externa.",
             "Negative bars: a deficit, meaning the country relies on foreign financing."),
    "g_deuda": ("Deuda bruta del Gobierno (% del PIB)", "Central government gross debt (% of GDP)"),
    "h_deuda": ("Deuda del Gobierno Nacional Central al cierre de cada año.", "Central government debt at the end of each year."),

    # --- tablas
    "q_todos": ("Todos los indicadores", "All indicators"),
    "resp_todos": ("Cada fila muestra el último dato, cuánto cambió y si hoy está alto o bajo comparado con su propia historia desde 2010.",
                   "Each row shows the latest value, how much it changed and whether it is high or low compared with its own history since 2010."),
    "col_ind": ("Indicador", "Indicator"), "col_ult": ("Último dato", "Latest"), "col_fecha": ("Período", "Period"),
    "col_cambio": ("Cambio", "Change"), "col_hist": ("Frente a su historia", "Versus its history"),
    "en_3m": ("en 3 meses", "over 3 months"), "en_12m": ("en 12 meses", "over 12 months"),
    "niv_muy_bajo": ("Muy bajo", "Very low"), "niv_bajo": ("Bajo", "Low"), "niv_normal": ("Normal", "Normal"),
    "niv_alto": ("Alto", "High"), "niv_muy_alto": ("Muy alto", "Very high"),
    "q_fuentes": ("Fuentes y actualización", "Sources and updates"),
    "resp_fuentes": ("Todos los datos se descargan automáticamente de las fuentes oficiales (cada hora en días hábiles las series diarias; todas las fuentes cada noche) y pasan controles de calidad antes de publicarse.",
                     "All data are downloaded automatically from official sources (daily series every hour on business days; all sources every night) and pass quality checks before publication."),
    "col_fuente": ("Fuente", "Source"), "col_frec": ("Frecuencia", "Frequency"), "col_ultimo": ("Último dato", "Latest"),
    "col_estado": ("Estado", "Status"),
    "fr_trimestral": ("Trimestral", "Quarterly"), "fr_mensual": ("Mensual", "Monthly"), "fr_diaria": ("Diaria", "Daily"),
    "fr_diaria_mercado": ("Diaria", "Daily"), "fr_anual": ("Anual", "Annual"),
    "fr_semanal": ("Semanal", "Weekly"),
    "st_vigente": ("Al día", "Up to date"), "st_rezagado": ("Retrasado", "Delayed"), "st_pendiente": ("Pendiente", "Pending"),
    "descargar": ("Descargar datos (CSV)", "Download data (CSV)"), "documentos": ("Documentos", "Documents"),
    "metodologia": ("Metodología", "Methodology"), "manual": ("Manual (PDF)", "Manual (PDF)"),
    "glosario": ("Glosario", "Glossary"),

    # --- cambios en los graficos
    "vs_ano": ("vs. hace 1 año", "vs. 1 year ago"), "vs_trim": ("vs. trimestre anterior", "vs. previous quarter"),
    "vs_mes": ("vs. hace 1 mes", "vs. 1 month ago"),
    "inf_mes": ("Variación del mes", "Monthly change"),
    "g_cc_corto": ("Cuenta corriente", "Current account"), "g_deuda_corto": ("Deuda del Gobierno", "Government debt"),

    # --- paneles de cambio
    "panel_cambio": ("Cambio", "Change"),

    # --- bolsa por dentro
    "nav_empresas": ("Sector empresarial", "Corporate sector"),
    "q_empresas": ("¿Qué empresas mueven la bolsa?", "Which companies move the market?"),
    "resp_empresas": ("Las 7 Magníficas de la bolsa colombiana —las siete empresas de mayor peso en el COLCAP: {n}— suman {p}% del índice. En los últimos doce meses el COLCAP varió {c}%, un índice donde todas las acciones pesan igual {e}% y las 7 Magníficas {m}%.",
                      "Colombia's Magnificent 7 —the seven largest companies in the COLCAP: {n}— make up {p}% of the index. Over the past twelve months the COLCAP moved {c}%, an equal-weighted index of all its stocks {e}% and the Magnificent 7 {m}%."),
    "resp_conc_si": ("Como el COLCAP sube más que el promedio de las acciones, las ganancias se concentran en las empresas más grandes.",
                     "Since the COLCAP beats the average stock, gains are concentrated in the largest companies."),
    "resp_conc_no": ("Como el promedio de las acciones sube más que el COLCAP, el avance es amplio y no depende solo de las grandes.",
                     "Since the average stock beats the COLCAP, the rally is broad and does not rely only on the largest names."),
    "resp_conc_igual": ("El COLCAP y el promedio de las acciones se mueven parecido: el avance es parejo entre grandes y pequeñas.",
                        "The COLCAP and the average stock move alike: performance is even across large and small names."),
    "g_indices": ("COLCAP, equiponderado y 7 Magníficas (base 100)", "COLCAP, equal-weighted and Magnificent 7 (base 100)"),
    "h_indices": ("Las tres líneas parten de 100 al inicio del periodo elegido arriba (3, 5, 10 años o todo). Azul: el COLCAP oficial, donde pesan más las empresas grandes. Verde: todas las acciones pesan igual. Naranja: solo las 7 Magníficas, con igual peso. Abajo, la rentabilidad de 12 meses de cada una.",
                  "All three lines start at 100 at the beginning of the period chosen above (3, 5, 10 years or all). Blue: the official COLCAP, where large companies weigh more. Green: every stock weighs the same. Orange: only the Magnificent 7, equally weighted. Below, each one's 12-month return."),
    "idx_colcap": ("COLCAP oficial", "Official COLCAP"), "idx_equi": ("Equiponderado", "Equal-weighted"),
    "idx_mag": ("7 Magníficas", "Magnificent 7"),
    "rent_12m": ("rentabilidad en 12 meses", "12-month return"),
    "g_pesos": ("Cuánto pesa cada acción en el COLCAP ({f})", "Weight of each stock in the COLCAP ({f})"),
    "h_pesos": ("Las barras naranjas son las 7 Magníficas (si una empresa tiene acción ordinaria y preferencial, se suman). Un peso alto significa que esa acción mueve mucho el índice.",
                "Orange bars are the Magnificent 7 (common and preferred shares of the same company are added up). A high weight means that stock moves the index a lot."),
    "t_magnificas": ("Las 7 Magníficas hoy", "The Magnificent 7 today"),
    "col_empresa": ("Empresa", "Company"), "col_peso": ("Peso en COLCAP", "COLCAP weight"), "col_precio": ("Precio", "Price"),
    "col_1m": ("1 mes", "1 month"), "col_ano": ("En el año", "Year to date"), "col_12m": ("12 meses", "12 months"),
    "m_empresas": ("Método: canasta y pesos del fondo iShares MSCI COLCAP (BlackRock), que replica el índice, actualizados a diario. Precios de cierre semanales de Yahoo Finance (sin dividendos, como el COLCAP). Las 7 Magníficas son las siete empresas de mayor peso y se recalculan con cada canasta. Equiponderado y 7 Magníficas: promedio simple de los retornos semanales de sus acciones (rebalanceo semanal); se descartan retornos semanales mayores a ±60% por ser errores de la fuente. Usa la canasta vigente hacia atrás, por lo que omite empresas que salieron del índice (sesgo de supervivencia).",
                   "Method: basket and weights of the iShares MSCI COLCAP fund (BlackRock), which tracks the index, updated daily. Weekly closing prices from Yahoo Finance (price only, like the COLCAP). The Magnificent 7 are the seven largest companies and are recomputed with each basket. Equal-weighted and Magnificent 7: simple average of weekly stock returns (weekly rebalancing); weekly returns beyond ±60% are dropped as source errors. The current basket is applied backwards, so companies that left the index are omitted (survivorship bias)."),

    # --- reloj del ciclo (vista principal)
    "nav_ciclo": ("Ciclo", "Cycle"),
    "q_ciclo": ("¿En qué parte del ciclo está la economía?", "Where is the economy in its cycle?"),
    "resp_ciclo": ("En {q} la economía está en <b>{fase}</b>: produce {nivel} y, en los últimos dos trimestres, esa diferencia {dir}. {racha}",
                   "In {q} the economy is in <b>{fase}</b>: it is producing {nivel} and, over the last two quarters, that gap {dir}. {racha}"),
    "ck_racha1": ("Es su primer trimestre en esta fase.", "It is the first quarter in this phase."),
    "ck_rachan": ("Lleva {n} trimestres seguidos en esta fase.", "It has been {n} quarters in a row in this phase."),
    "ck_trim1": ("trimestre", "quarter"),
    "fd_expansion": ("Expansión: produce por encima de su capacidad y cada vez más; suele traer presión sobre precios.",
                     "Expansion: output above capacity and rising; usually brings price pressure."),
    "fd_desaceleracion": ("Desaceleración: sigue por encima de su capacidad, pero perdiendo impulso.",
                          "Slowdown: still above capacity, but losing momentum."),
    "fd_contraccion": ("Contracción: produce por debajo de su capacidad y la distancia aumenta.",
                       "Contraction: output below capacity and the shortfall is widening."),
    "fd_recuperacion": ("Recuperación: aún por debajo de su capacidad, pero acercándose.",
                        "Recovery: still below capacity, but closing in."),
    "ck_ver": ("Trimestre:", "Quarter:"), "ck_estela": ("Recorrido", "Trail"),
    "ck_1a": ("1 año de recorrido", "1-year trail"), "ck_2a": ("2 años", "2 years"), "ck_3a": ("3 años", "3 years"),
    "ck_fase": ("Fase", "Phase"), "ck_brecha": ("Nivel: producción frente a su capacidad", "Level: output vs capacity"),
    "ck_dir": ("Dirección: cambio en 2 trimestres", "Direction: change over 2 quarters"),
    "ck_racha": ("Trimestres seguidos en la fase", "Quarters in a row in this phase"),
    "ck_encima": ("{v}% por encima de su capacidad", "{v}% above capacity"),
    "ck_debajo": ("{v}% por debajo de su capacidad", "{v}% below capacity"),
    "ck_mejora": ("aumentó {v} puntos", "rose {v} points"), "ck_empeora": ("disminuyó {v} puntos", "fell {v} points"),
    "ck_trim": ("trimestres", "quarters"),
    "ck_hist_x": ("Trimestre", "Quarter"),
    "ck_hist_y": ("Brecha: producción frente a su capacidad (%) · línea: cambio en 2 trimestres (pp)", "Gap: output vs capacity (%) · line: 2-quarter change (pp)"),
    "ck_eje_x": ("Nivel: producción frente a su capacidad (%)", "Level: output vs capacity (%)"),
    "ck_eje_y": ("Dirección (cambio en 2 trimestres, pp)", "Direction (2-quarter change, pp)"),
    "ck_hover": ("Nivel", "Level"), "vs_2t": ("en 2 trimestres", "over 2 quarters"),
    "g_reloj_main": ("Reloj del ciclo: dónde estamos y hacia dónde vamos", "Cycle clock: where we are and where we are heading"),
    "h_reloj_main": ("Cada punto es un trimestre y las flechas muestran el recorrido; el punto grande es el trimestre elegido. Derecha: la economía produce por encima de su capacidad. Arriba: esa diferencia está aumentando. La economía suele girar en el sentido del reloj: expansión → desaceleración → contracción → recuperación.",
                     "Each dot is a quarter and arrows show the path; the large dot is the selected quarter. Right: output above capacity. Up: that gap is widening. The economy usually turns clockwise: expansion → slowdown → contraction → recovery."),
    "g_ciclo_hist": ("Recorrido del ciclo trimestre a trimestre", "The cycle quarter by quarter"),
    "h_ciclo_hist": ("Cada barra es la distancia entre lo que produce la economía y su capacidad, coloreada por fase. Pase el cursor o haga clic en un trimestre para ubicarlo en el reloj. La franja gris marca el recorrido que se ve en el reloj.",
                     "Each bar is the distance between output and capacity, colored by phase. Hover or click a quarter to place it on the clock. The grey band marks the path shown on the clock."),

    # --- sectores
    "nav_sectores": ("Sectores", "Sectors"), "nav_informal": ("Empleo", "Jobs"), "nav_cap": ("Capacidad", "Capacity"),
    "q_sectores": ("¿Qué sectores impulsan la economía?", "Which sectors drive the economy?"),
    "resp_sectores": ("En {q} los sectores que más crecieron fueron {s1} ({v1}%) y {s2} ({v2}%). El que más aportó al crecimiento fue {a}, con {ap} de los {tot} puntos de crecimiento del valor agregado, porque además de crecer es uno de los más grandes.",
                      "In {q} the fastest-growing sectors were {s1} ({v1}%) and {s2} ({v2}%). The largest contributor was {a}, with {ap} of the {tot} points of value-added growth, because it is also one of the largest sectors."),
    "resp_sec_neg": ("Se contrajeron: {lista}.", "Contracting: {lista}."),
    "resp_sec_todos": ("Ningún sector se contrajo.", "No sector contracted."),
    "g_sec_barras": ("Crecimiento anual por sector ({q})", "Annual growth by sector ({q})"),
    "h_sec_barras": ("Barras: cuánto creció cada sector frente al mismo trimestre del año anterior (azul crece, naranja cae). La raya vertical es el dato de hace un año: si la barra la supera, el sector se aceleró. Pase el cursor para ver su peso en la economía y cuántos puntos aportó.",
                     "Bars: each sector's growth versus the same quarter a year earlier (blue grows, orange falls). The vertical tick is the figure a year ago: if the bar goes past it, the sector accelerated. Hover to see its weight in the economy and how many points it contributed."),
    "g_sec_mapa": ("Mapa del crecimiento por sector, trimestre a trimestre", "Growth map by sector, quarter by quarter"),
    "h_sec_mapa": ("Cada casilla es un sector en un trimestre: azul intenso, crecimiento alto; naranja, caída. Los sectores están ordenados por tamaño (los más grandes arriba). Se ve de un vistazo qué sectores cayeron en 2020 y cuáles lideran hoy. Haga clic en cualquier casilla para ver ese trimestre en las barras.",
                   "Each cell is a sector in a quarter: deep blue, strong growth; orange, contraction. Sectors are ordered by size (largest at the top). At a glance you can see which sectors fell in 2020 and which lead today. Click any cell to see that quarter in the bar chart."),
    "m_sectores": ("Método: PIB por el lado de la oferta, 12 agrupaciones CIIU Rev. 4 del DANE (series encadenadas de volumen, año base 2015, datos originales). Crecimiento anual = variación frente al mismo trimestre del año anterior. Aporte (pp) = cambio del nivel del sector en un año dividido por el valor agregado total de hace un año; como los volúmenes encadenados no son aditivos, la suma de aportes difiere levemente del crecimiento total.",
                   "Method: supply-side GDP, DANE's 12 ISIC Rev. 4 groupings (chain-linked volumes, base year 2015, original data). Annual growth = change versus the same quarter a year earlier. Contribution (pp) = one-year change in the sector's level divided by total value added a year earlier; chain-linked volumes are not additive, so contributions do not add up exactly to total growth."),
    "sec_raya": ("Raya: hace un año ({q})", "Tick: a year earlier ({q})"),
    "sec_crec": ("Crecimiento anual", "Annual growth"), "sec_hace": ("Hace un año", "A year ago"),
    "sec_peso": ("Peso en la economía", "Share of the economy"), "sec_aporte": ("Aporte al crecimiento", "Contribution to growth"),

    # --- informalidad
    "q_informal": ("¿Cómo está el empleo y cuánto es informal?", "How are jobs doing, and how much employment is informal?"),
    "resp_desempleo": ("La tasa de desempleo fue {v}% en {f} (hace un año: {a}%).", "The unemployment rate was {v}% in {f} (a year earlier: {a}%)."),
    "q_cap": ("¿Produce la economía por encima o por debajo de su capacidad?", "Is the economy producing above or below its capacity?"),
    "resp_cap": ("En el {q} la economía produjo {g}% frente a su capacidad estimada: {e}.", "In {q} the economy produced {g}% relative to its estimated capacity: {e}."),
    "cap_encima": ("está por encima, sin holgura, lo que tiende a presionar los precios", "it is above, with no slack, which tends to push prices up"),
    "cap_debajo": ("está por debajo, con capacidad ociosa, lo que tiende a moderar los precios", "it is below, with idle capacity, which tends to ease prices"),
    "x_crec_pa": ("Hay dos formas de medir el crecimiento. La trimestral (primer gráfico) compara cada trimestre con el mismo del año anterior y reacciona rápido. La anual (segundo gráfico) suma los cuatro trimestres de cada año y muestra la tendencia de fondo, sin el ruido de un solo trimestre. Ambas descuentan la inflación: miden cuánto más se produjo, no cuánto subieron los precios. La sección siguiente descompone ese crecimiento por sectores.",
                  "There are two ways to measure growth. The quarterly one (first chart) compares each quarter with the same quarter a year earlier and reacts quickly. The annual one (second chart) adds up the four quarters of each year and shows the underlying trend, without the noise of a single quarter. Both are net of inflation: they measure how much more was produced, not how much prices rose. The next section breaks this growth down by sector."),
    "resp_informal": ("En el trimestre {p}, el {v}% de las personas ocupadas en Colombia trabajaba en la informalidad ({m} millones de personas), frente a {a}% un año antes. En las 13 principales ciudades la proporción es menor ({c}%). Al inicio de la serie, en 2021, era {i}%.",
                      "In the {p} rolling quarter, {v}% of employed people in Colombia worked informally ({m} million people), versus {a}% a year earlier. In the 13 main cities the share is lower ({c}%). At the start of the series, in 2021, it was {i}%."),
    "g_informal": ("Proporción de ocupados informales", "Share of informal workers"),
    "h_informal": ("Porcentaje de las personas ocupadas que trabajan sin seguridad social o en negocios no registrados (definición del DANE). Cada punto es un trimestre móvil. Abajo, el cambio frente a un año antes: barras naranjas = la informalidad bajó.",
                   "Share of employed people working without social security or in unregistered businesses (DANE definition). Each point is a rolling quarter. Below, the change versus a year earlier: orange bars = informality fell."),
    "g_inf_ramas": ("Informalidad por sector ({p})", "Informality by sector ({p})"),
    "h_inf_ramas": ("Porcentaje de los ocupados de cada sector que son informales. La raya vertical es el dato de hace un año. Pase el cursor para ver cuántas personas son.",
                    "Share of each sector's workers who are informal. The vertical tick is the figure a year earlier. Hover to see how many people that is."),
    "m_informal": ("Método: DANE, Gran Encuesta Integrada de Hogares, medición de empleo informal y seguridad social (resolución 0203 de 2023, basada en la OIT). Trimestres móviles desde 2021, total nacional y 13 ciudades con áreas metropolitanas. La tasa por sector = ocupados informales / ocupados del sector. No es comparable con la serie anterior a 2021 (otra definición y marco muestral).",
                   "Method: DANE, Integrated Household Survey, informal employment and social security (Resolution 0203 of 2023, ILO-based). Rolling quarters since 2021, national total and 13 cities with metro areas. Sector rate = informal workers / sector workers. Not comparable with the pre-2021 series (different definition and sample frame)."),
    "inf_nal": ("Total nacional", "National total"), "inf_13": ("13 ciudades (promedio)", "13 cities (average)"),
    "inf_hoy": ("Último dato", "Latest"), "inf_tasa": ("Informalidad", "Informality"),
    "inf_personas": ("Informales / ocupados", "Informal / employed"),
    "mov_1": ("nov–ene", "Nov–Jan"),
    "mov_2": ("dic–feb", "Dec–Feb"),
    "mov_3": ("ene–mar", "Jan–Mar"),
    "mov_4": ("feb–abr", "Feb–Apr"),
    "mov_5": ("mar–may", "Mar–May"),
    "mov_6": ("abr–jun", "Apr–Jun"),
    "mov_7": ("may–jul", "May–Jul"),
    "mov_8": ("jun–ago", "Jun–Aug"),
    "mov_9": ("jul–sep", "Jul–Sep"),
    "mov_10": ("ago–oct", "Aug–Oct"),
    "mov_11": ("sep–nov", "Sep–Nov"),
    "mov_12": ("oct–dic", "Oct–Dec"),

    # --- publicaciones oficiales
    "nav_noticias": ("Noticias", "News"),
    "q_noticias": ("Nota: últimas publicaciones oficiales", "Note: latest official releases"),
    "resp_noticias": ("El dato más reciente de cada fuente, en una línea, con enlace a la página oficial. Se actualiza sola cada hora en días hábiles.",
                      "The latest figure from each source, in one line, linking to the official page. Updated automatically every hour on business days."),
    "nt_fecha": ("{f}", "{f}"), "nt_dato": ("dato más reciente", "latest figure"),
    "nt_salas": ("Salas de prensa oficiales", "Official press rooms"),
    "menu_ocultar": ("Mostrar u ocultar el menú de secciones", "Show or hide the section menu"),
    "menu_btn_ocultar": ("Ocultar menú", "Hide menu"), "menu_btn_mostrar": ("Secciones", "Sections"),

    # --- producción y capacidad, PIB en pesos
    "g_cap": ("Lo que produce la economía frente a su capacidad", "What the economy produces versus its capacity"),
    "h_cap": ("La línea punteada es la capacidad: lo máximo que la economía puede producir de forma sostenida, sin generar presiones de inflación (como una frontera de posibilidades de producción que se mueve con el tiempo). La línea azul es lo que realmente produjo. Verde: produce por encima de su capacidad (se calienta). Naranja: produce por debajo (hay holgura: capacidad ociosa, desempleo). Abajo, la distancia en %.",
              "The dotted line is capacity: the most the economy can produce sustainably without creating inflation pressure (like a production possibility frontier that shifts over time). The blue line is what it actually produced. Green: output above capacity (overheating). Orange: below capacity (slack: idle capacity, unemployment). Below, the distance in %."),
    "cap_pot": ("Capacidad (PIB potencial)", "Capacity (potential GDP)"), "cap_real": ("PIB real", "Real GDP"),
    "cap_dif": ("Distancia a la capacidad", "Distance to capacity"),
    "cap_sobre": ("Por encima: se calienta", "Above: overheating"), "cap_holgura": ("Por debajo: holgura", "Below: slack"),
    "cap_panel": ("Distancia a la capacidad (%)", "Distance to capacity (%)"),
    "cap_eje": ("Billones de COP de 2015 por trimestre", "COP trillions (2015 prices) per quarter"),
    "g_pa": ("Crecimiento real de la economía por año", "Real economic growth by year"),
    "h_pa": ("Cada barra es un año: cuánto creció la producción del país, descontando la inflación, frente al año anterior (azul: creció; naranja: cayó). La barra clara es el año en curso: el crecimiento de los últimos 12 meses. La línea verde punteada es el ritmo habitual (potencial) y la discontinua gris, el promedio 2010–2019, como referencia.",
             "Each bar is a year: how much the country's output grew, net of inflation, versus the previous year (blue: grew; orange: fell). The light bar is the current year: growth over the last 12 months. The dotted green line is the usual (potential) pace and the dashed grey line the 2010–2019 average, for reference."),
    "pa_anual": ("Crecimiento real anual", "Annual real growth"), "pa_vs": ("vs. año anterior", "vs. previous year"),
    "pa_12m": ("Últimos 12 meses (a {q})", "Last 12 months (to {q})"),
    "pa_prom": ("Promedio 2010–2019: {v}%", "2010–2019 average: {v}%"),
    "pa_eje": ("Crecimiento real (%)", "Real growth (%)"),
    "pa_franja": ("Crecimiento real, últimos 12 meses", "Real growth, last 12 months"),
    "pa_resp": ("En los últimos 12 meses (hasta el {q}) la economía creció {v}% en términos reales; en {a} creció {va}% (promedio 2010–2019: {p}%).",
                "Over the last 12 months (to {q}) the economy grew {v}% in real terms; in {a} it grew {va}% (2010–2019 average: {p}%)."),
    "x_crec": ("Hoy la economía produce {g}% frente a su capacidad: COP ${y} billones (pesos de 2015) en el trimestre, frente a una capacidad estimada de COP ${pot} billones. Cuando produce por encima, las empresas trabajan a tope, el empleo se estrecha y los precios tienden a subir; cuando produce por debajo, sobra capacidad y la inflación tiende a ceder.",
               "Today the economy produces {g}% versus its capacity: COP {y} trillion (2015 pesos) in the quarter, against an estimated capacity of COP {pot} trillion. Above capacity, firms run at full tilt, labour gets tight and prices tend to rise; below it, there is spare capacity and inflation tends to ease."),
    "x_crec2": ("La capacidad no se observa directamente: se estima con la tendencia del PIB. Por eso es una guía, no una cifra exacta; lo importante es la dirección (si la distancia crece o se cierra), que es lo que usa el reloj del ciclo al inicio de la página.",
                "Capacity is not observed directly: it is estimated from GDP's trend. It is a guide, not an exact figure; what matters is the direction (whether the gap widens or closes), which is what the cycle clock at the top uses."),
    "x_precios": ("Además de la inflación de hoy, importa lo que la gente y los mercados creen que pasará: si esperan inflación alta, suben precios y salarios por adelantado y la inflación se vuelve persistente. El gráfico de abajo muestra lo que el mercado espera para dentro de 5 a 10 años: si está cerca de 3%, confía en que el Banco de la República cumplirá su meta.",
                  "Beyond today's inflation, what people and markets believe will happen matters: if they expect high inflation, they raise prices and wages in advance and inflation becomes persistent. The chart below shows what the market expects 5 to 10 years ahead: near 3% means it trusts the central bank to meet its target."),
    "x_real": ("¿Qué es la tasa real ex ante? Es la tasa de interés del Banco menos la inflación que se espera para el próximo año. Hoy: {v}% de tasa del Banco y {e}% de inflación esperada dan una tasa real de {r}%. «Ex ante» significa «antes de que ocurra»: usa la inflación esperada, no la que ya pasó, porque quien pide un crédito hoy decide pensando en la inflación futura.",
               "What is the ex-ante real rate? It is the central bank's rate minus the inflation expected for next year. Today: a {v}% policy rate and {e}% expected inflation give a {r}% real rate. \"Ex ante\" means \"before the fact\": it uses expected inflation, not past inflation, because whoever borrows today decides with future inflation in mind."),
    "x_real2": ("Se compara con la tasa neutral (2,7%–3,0%, estimación del Banco): la que ni acelera ni frena la economía. Si la tasa real está por encima, el crédito es caro y la economía se enfría (política restrictiva); si está por debajo, se estimula (política expansiva).",
                "It is compared with the neutral rate (2.7%–3.0%, the Bank's estimate): the one that neither speeds up nor slows the economy. Above it, credit is expensive and the economy cools (tight policy); below it, the economy is stimulated (loose policy)."),
    "x_curva": ("La curva resume cuánto pide el mercado por prestarle al Gobierno a distintos plazos. Si sube toda la curva, se encarece el crédito para todos (empresas, hogares, el propio Gobierno). Compare años: en 2021 las tasas eran bajas y la curva muy empinada (se esperaban alzas); en 2022–2023 subió con fuerza cuando el Banco combatió la inflación.",
                "The curve shows what the market asks to lend to the government at different maturities. When the whole curve rises, credit gets more expensive for everyone (firms, households, the government itself). Compare years: in 2021 rates were low and the curve steep (hikes expected); in 2022–2023 it rose sharply as the central bank fought inflation."),
    "x_mercados": ("El dólar alto encarece importaciones y deudas en dólares, pero ayuda a exportadores. Para comparar con otros países se usa la tasa de cambio real (abajo): corrige por la inflación de Colombia y de sus socios comerciales. Por encima de 100, el peso está «barato» frente a su promedio histórico.",
                   "A strong dollar makes imports and dollar debts more expensive but helps exporters. To compare with other countries the real exchange rate (below) corrects for Colombian and trading partners' inflation. Above 100, the peso is \"cheap\" versus its historical average."),
    "x_sectores": ("El PIB se divide en 12 grandes sectores. Un sector puede crecer mucho y aportar poco si es pequeño (por ejemplo, minería), y uno grande que crezca poco puede mover todo el total (comercio, gobierno, industria). Por eso, al pasar el cursor, cada barra muestra su peso y cuántos puntos aportó al crecimiento.",
                   "GDP is split into 12 major sectors. A sector can grow a lot and contribute little if it is small (e.g. mining), while a large one growing slowly can move the total (trade, government, manufacturing). That is why each bar shows its weight and contribution on hover."),

    # --- selectores
    "sec_ver": ("Ver el trimestre:", "Show quarter:"),
    "inf_13c": ("13 ciudades principales", "13 main cities"), "inf_23c": ("Otras ciudades (23 en total)", "Other cities (23 in total)"),
    "g_inf_ciudades": ("Informalidad por ciudad ({p})", "Informality by city ({p})"),
    "h_inf_ciudades": ("Porcentaje de los ocupados que son informales en cada ciudad. En azul, las 13 ciudades principales; en gris, las otras 10 capitales que completan las 23. La raya vertical es el dato de hace un año.",
                       "Share of workers who are informal in each city. In blue, the 13 main cities; in grey, the other 10 capitals that complete the 23. The vertical tick is the figure a year earlier."),
    "x_informal": ("Las 13 ciudades principales son: {lista}. «A.M.» significa área metropolitana (la ciudad y sus municipios vecinos). La informalidad es mayor en el campo y en las ciudades más pequeñas porque allí predominan el trabajo por cuenta propia y los negocios sin registro; por eso el total nacional (que incluye zonas rurales) supera al de las ciudades.",
                   "The 13 main cities are: {lista}. \"A.M.\" means metropolitan area (the city and its neighbouring municipalities). Informality is higher in rural areas and smaller cities, where self-employment and unregistered businesses dominate; that is why the national total (which includes rural areas) exceeds the cities'."),

    # --- decision anunciada de la Junta
    "an_sube": ("Anunciada: sube", "Announced: hike"), "an_baja": ("Anunciada: baja", "Announced: cut"),
    "an_detalle": ("Decisión de la Junta del {a} (antes {p}%)<br>Rige desde el {v}", "Board decision on {a} (previously {p}%)<br>Effective {v}"),
    "an_resp": ("El {a} la Junta Directiva anunció un cambio de la tasa de {p}% a {n}%, que rige desde el {v}; la serie oficial la registra ese día.",
                "On {a} the Board announced a policy rate change from {p}% to {n}%, effective {v}; the official series records it that day."),
    "an_marca": ("Decisión anunciada", "Announced decision"), "an_hover": ("Anunciada el {a}", "Announced on {a}"),
    "construido": ("página actualizada", "page updated"),

    # --- curva TES
    "nav_curva": ("Curva TES", "TES curve"),
    "q_curva": ("¿Cuánto cobra el mercado por prestarle al Gobierno?", "What does the market charge to lend to the government?"),
    "resp_curva": ("Al {f}, un bono del Gobierno a 1 año rinde {c}% y uno a 10 años {l}%. La diferencia entre ambos es {p} puntos: la curva está {forma}. En el último año la tasa a 10 años cambió {d} puntos. Mueva la barra de fechas para ver la curva de cualquier día desde 2003 y marque años para compararlos.",
                   "On {f}, a 1-year government bond yields {c}% and a 10-year bond {l}%. The gap is {p} points: the curve is {forma}. Over the past year the 10-year yield moved {d} points. Move the date bar to see the curve on any day since 2003 and tick years to compare them."),
    "tes_normal": ("con pendiente positiva (normal)", "upward-sloping (normal)"),
    "tes_plana": ("casi plana", "almost flat"), "tes_invertida": ("invertida (el corto plazo paga más que el largo)", "inverted (short rates above long rates)"),
    "tes_tipo": ("Tipo de bono", "Bond type"),
    "tes_pesos": ("TES en pesos (tasa nominal)", "Peso TES (nominal yield)"),
    "tes_uvr": ("TES en UVR (tasa real)", "UVR TES (real yield)"),
    "tes_fecha": ("Curva del", "Curve on"),
    "tes_volver": ("Volver al último dato", "Back to latest"),
    "tes_comparar": ("Comparar con el cierre de:", "Compare with year-end:"),
    "tes_g_curva": ("Curva cero cupón de los TES (BanRep)", "TES zero-coupon yield curve (BanRep)"),
    "tc_q": ("¿Cómo se calcula la TRM y qué es la tasa de cambio real?", "How is the TRM computed and what is the real exchange rate?"),
    "tes_q": ("¿Qué es la curva cero cupón de los TES?", "What is the TES zero-coupon curve?"),
    "tes_h_curva": ("Cada línea es una fecha: la línea azul gruesa es la fecha elegida y las demás son los años marcados. Una curva que sube de izquierda a derecha es lo normal; si baja, el mercado espera tasas menores en el futuro.",
                    "Each line is one date: the thick blue line is the selected date and the others are the ticked years. A curve rising from left to right is normal; if it falls, the market expects lower rates ahead."),
    "tes_g_hist": ("Historia de las tasas a 1, 5 y 10 años", "History of 1-, 5- and 10-year yields"),
    "tes_h_hist": ("Pase el cursor sobre la historia para ver la curva de ese día; haga clic para fijarla. La línea vertical marca la fecha elegida.",
                   "Hover over the history to see that day's curve; click to pin it. The vertical line marks the selected date."),
    "tes_pend": ("Pendiente 10 años − 1 año", "Slope 10y − 1y"),
    "m_curva": ("Método: tasas cero cupón de los TES publicadas a diario por el Banco de la República (series 15272–15277) para plazos de 1, 5 y 10 años, en pesos (nominales) y en UVR (reales). La comparación por años usa el último día hábil de cada año. El cambio se mide en puntos porcentuales frente a la observación más cercana un año antes de la fecha elegida.",
                "Method: TES zero-coupon yields published daily by Banco de la República (series 15272–15277) for 1-, 5- and 10-year tenors, in pesos (nominal) and UVR (real). Year comparisons use each year's last business day. Changes are in percentage points against the closest observation one year before the selected date."),
    # --- interfaz v12 (terminal de vidrio)
    "lo_clave": ("Lo clave", "Key points"),
    "tema_btn": ("Cambiar entre tema oscuro y claro", "Switch between dark and light theme"),
    "tema_oscuro": ("Oscuro", "Dark"),
    "tema_claro": ("Claro", "Light"),
    "kicker_monitor": ("Monitor del ciclo económico", "Economic cycle monitor"),
    "ph_brecha": ("Brecha", "Gap"), "ph_dir": ("Dirección", "Direction"), "ph_racha": ("Racha", "Streak"),
    "fuentes_corto": ("Fuentes: DANE · Banco de la República · BVC/MSCI", "Sources: DANE · Banco de la República · BVC/MSCI"),
    "ir_a": ("Ir a la sección", "Go to section"),
    # --- estructura v12: portada concisa + paginas de detalle
    "nav_inflacion": ("Inflación", "Inflation"), "nav_externo": ("Externo y fiscal", "External & fiscal"),
    "nav_aria": ("Secciones", "Sections"), "ruta": ("Ruta", "Breadcrumb"), "inicio": ("Tablero", "Dashboard"),
    "anterior": ("Anterior", "Previous"), "siguiente": ("Siguiente", "Next"), "volver_tablero": ("Volver al tablero", "Back to dashboard"),
    "tablero": ("Tablero por tema", "Dashboard by topic"),
    "tablero_t": ("Lo esencial, tema por tema", "The essentials, topic by topic"),
    "tablero_d": ("Un gráfico y dos ideas por tema. Cada tema abre una página con el análisis completo.",
                  "One chart and two takeaways per topic. Each topic opens a page with the full analysis."),
    "cta_ciclo": ("Ver el reloj del ciclo", "Open the cycle clock"),
    "cta_crec": ("Entender más sobre el crecimiento", "More on growth"),
    "cta_inflacion": ("Entender más sobre la inflación", "More on inflation"),
    "cta_empleo": ("Entender más sobre el empleo", "More on jobs"),
    "cta_tasas": ("Entender más sobre las tasas de interés", "More on interest rates"),
    "cta_mercados": ("Entender más sobre el peso y el dólar", "More on the peso and the dollar"),
    "cta_externo": ("Entender más sobre las cuentas externas y fiscales", "More on external and fiscal accounts"),
    "cta_indicadores": ("Ver los 16 indicadores, publicaciones oficiales y fuentes", "See all 16 indicators, official releases and sources"),
    "pg_ciclo": ("El ciclo económico", "The business cycle"),
    "pl_ciclo": ("En qué fase está la economía, cómo llegó ahí y hacia dónde se mueve, trimestre a trimestre desde 2014.",
                 "Which phase the economy is in, how it got there and where it is heading, quarter by quarter since 2014."),
    "pg_crec": ("Crecimiento, sectores y demanda", "Growth, sectors and demand"),
    "pl_crec": ("Cuánto crece la economía y por qué: por la oferta (los 12 sectores del PIB) y por la demanda (hogares, Gobierno, inversión y comercio exterior), con el PIB por persona y la productividad.",
                "How fast the economy grows and why: from the supply side (the 12 GDP sectors) and the demand side (households, government, investment and trade), with GDP per person and productivity."),
    "pg_empleo": ("Empleo e informalidad", "Jobs and informality"),
    "pl_empleo": ("Cuántos trabajan, dónde y cómo: desempleo, informalidad, empleo por sector y por tipo de contrato, brechas entre mujeres y hombres, jóvenes, campo y ciudad, y las 32 capitales.",
                  "How many work, where and how: unemployment, informality, jobs by sector and by type of work, gaps between women and men, young people, urban and rural areas, and the 32 capital cities."),
    "pg_inflacion": ("Inflación y precios", "Inflation and prices"),
    "pl_inflacion": ("Cuánto suben los precios frente a la meta del Banco de la República, qué inflación espera el mercado y de dónde viene: divisiones, bienes y servicios, 188 subclases, niveles de ingreso y 23 ciudades.",
                     "How fast prices rise against the central bank's target, what inflation the market expects and where it comes from: divisions, goods and services, 188 subclasses, income levels and 23 cities."),
    "pg_tasas": ("Tasas de interés", "Interest rates"),
    "pl_tasas": ("La tasa del Banco de la República y la tasa real: cuánto cuesta de verdad endeudarse.",
                 "The central bank's policy rate and the real rate: the true cost of borrowing."),
    "pg_mercados": ("El peso colombiano", "The Colombian peso"),
    "pl_mercados": ("El peso frente al dólar y a otras monedas, la tasa de cambio real y lo que mueve al peso: el dólar global, el petróleo y los flujos de divisas.", "The peso against the dollar and other currencies, the real exchange rate and what moves the peso: the global dollar, oil and foreign-currency flows."),
    "pg_externo": ("Cuentas externas y fiscales", "External and fiscal accounts"),
    "pl_externo": ("La balanza de pagos por componentes, cómo se financia, la inversión extranjera y las remesas, la deuda externa, y los ingresos, gastos, intereses, financiamiento y deuda del Gobierno.", "The balance of payments by component, how it is financed, foreign investment and remittances, external debt, and government revenue, spending, interest, financing and debt."),
    "nav_comercio": ("Comercio exterior", "Foreign trade"),
    "pg_comercio": ("Comercio exterior: qué vende y qué compra Colombia", "Foreign trade: what Colombia sells and buys"),
    "pl_comercio": ("Exportaciones e importaciones de bienes con las cifras oficiales del DANE y la DIAN: cuánto, qué, para qué y con quién.",
                    "Goods exports and imports from official DANE and DIAN figures: how much, what, for what and with whom."),
    "pd_expo12": ("Exportaciones, 12 meses", "Exports, 12 months"), "pd_bal12": ("Balanza comercial, 12 meses", "Trade balance, 12 months"),
    "pg_indicadores": ("Datos: indicadores, publicaciones y fuentes", "Data: indicators, releases and sources"),
    "pl_indicadores": ("Los 16 indicadores con su último dato y su nivel histórico, las publicaciones oficiales más recientes y el estado de cada fuente.",
                       "All 16 indicators with their latest value and historical level, the latest official releases and the status of every source."),
    "cp_alim": ("Alimentos", "Food"), "cp_reg": ("Regulados (energía, gas, transporte, combustibles)", "Regulated (utilities, transport, fuel)"),
    "cp_sinal": ("Todo menos alimentos", "All except food"), "cp_basica": ("De fondo (sin alimentos ni regulados)", "Underlying (ex food & regulated)"),
    "cp_total": ("Total", "Headline"), "base100_5a": ("base 100 hace 5 años", "base 100 five years ago"),
    "anunciada": ("anunciada el", "announced on"), "cp_raya": ("Hace un año", "A year ago"),
    "g_cp_barras": ("¿Qué precios suben más?", "Which prices are rising most?"),
    "h_cp_barras": ("Inflación anual de cada grupo de precios. La raya vertical es el dato de hace un año; la franja verde, el rango meta (2%–4%). Naranja: por encima del rango.",
                    "Annual inflation for each price group. The vertical tick is the figure a year ago; the green band is the 2%–4% target range. Orange: above the range."),
    "g_cp_lineas": ("Inflación por grupo de precios en el tiempo", "Inflation by price group over time"),
    "h_cp_lineas": ("Alimentos y regulados se mueven con choques (clima, energía, tarifas); la inflación de fondo muestra la presión persistente que el Banco de la República intenta controlar.",
                    "Food and regulated prices move with shocks (weather, energy, tariffs); underlying inflation shows the persistent pressure the central bank tries to control."),
    # --- portada de sondeo y menu agrupado
    "g_actividad": ("Actividad", "Activity"), "g_precios": ("Precios y tasas", "Prices & rates"), "g_mercados": ("Mercados y cuentas", "Markets & accounts"),
    "nav_datos": ("Datos", "Data"),
    "lectura_t": ("Lectura en un vistazo", "At a glance"),
    "lectura_d": ("Cada tema en una frase, con sus dos cifras clave. Abra el análisis para ver gráficos y detalle.",
                  "Each topic in one sentence, with its two key figures. Open the analysis for charts and detail."),
    "ver_analisis": ("Ver análisis", "Open analysis"),
    "fuentes_descargas": ("Fuentes y descargas", "Sources and downloads"),
    "aliados": ("Proyecto académico de la Universidad de San Buenaventura Cali, con el apoyo de FinancialTools.io en el Laboratorio de Trading.",
                "Academic project of Universidad de San Buenaventura Cali, supported by FinancialTools.io at the Trading Lab."),
    "sec_mas": ("Sector más dinámico", "Fastest-growing sector"), "sec_menos": ("Sector más débil", "Weakest sector"),
    "anual": ("anual", "y/y"),
    "tc_titulo": ("Curva TES · tasas en pesos", "TES curve · peso yields"), "tc_forma": ("Forma", "Shape"),
    "tc_normal": ("Normal", "Normal"), "tc_plana": ("Plana", "Flat"), "tc_invertida": ("Invertida", "Inverted"),
    "tc_cta": ("Explorar la curva día a día", "Explore the curve day by day"), "pend_corta": ("Pendiente 10a − 1a", "Slope 10y − 1y"),
    "tpm_real_corta": ("Tasa real (ex ante)", "Real rate (ex ante)"), "neutral_ref": ("neutral ≈ 2,7%–3,2%", "neutral ≈ 2.7%–3.2%"),
    "pg_sectores": ("Sectores de la economía", "Sectors of the economy"),
    "pl_sectores": ("Cuánto crece cada uno de los 12 sectores del PIB y cuánto aporta al crecimiento total, en cualquier trimestre desde 2010.",
                    "How fast each of the 12 GDP sectors grows and how much it contributes to total growth, in any quarter since 2010."),
    "pg_capacidad": ("Capacidad productiva: sectores, trabajo y regiones", "Productive capacity: sectors, labour and regions"),
    "pl_capacidad": ("Si la economía produce por encima o por debajo de lo que puede sostener sin generar inflación, y dónde: en qué sectores, en el mercado laboral y en cada departamento.",
                     "Whether the economy produces above or below what it can sustain without generating inflation, and where: by sector, in the labour market and in each department."),
    "pg_curva": ("Curva de rendimientos TES", "TES yield curve"),
    "pl_curva": ("Lo que cobra el mercado por prestarle al Gobierno a 1, 5 y 10 años, cualquier día desde 2003.",
                 "What the market charges to lend to the government at 1, 5 and 10 years, any day since 2003."),
    "pg_empresas": ("Las empresas de Colombia", "Colombia's companies"),
    "pl_empresas": ("Tamaño, rentabilidad, endeudamiento y concentración de las 10.000 empresas más grandes, sus sectores y regiones, la bolsa, el crédito a empresas y cuántas empresas nacen y cierran.", "Size, profitability, leverage and concentration of the 10,000 largest companies, their sectors and regions, the stock market, credit to firms and how many companies are born and close."),
}

GLOSARIO = {
    "es": [
        ("PIB", "Valor de todo lo que produce el país. Su variación anual mide el crecimiento de la economía."),
        ("Ritmo habitual (PIB potencial)", "Crecimiento que la economía puede sostener sin generar presiones sobre los precios."),
        ("Brecha del producto", "Diferencia entre lo que la economía produce y su capacidad sostenible, en % de esa capacidad."),
        ("Inflación", "Variación de los precios al consumidor en los últimos 12 meses (IPC del DANE)."),
        ("Meta de inflación", "El Banco de la República busca una inflación de 3%, con un margen de ±1 punto."),
        ("Inflación de fondo", "Inflación sin alimentos ni precios regulados (servicios públicos, combustibles), que son los más volátiles."),
        ("Tasa de política", "Tasa de interés que fija el Banco de la República y que sirve de referencia para los créditos."),
        ("Tasa real", "Tasa de interés descontando la inflación. Mide cuánto cuesta realmente el crédito."),
        ("Tasa neutral", "Tasa real que ni frena ni estimula la economía."),
        ("TES", "Bonos del Gobierno colombiano. Los TES en UVR se ajustan por inflación."),
        ("Inflación esperada por el mercado", "Inflación que se deduce de comparar TES a tasa fija con TES ajustados por inflación."),
        ("TRM", "Tasa representativa del mercado: pesos colombianos por dólar."),
        ("COLCAP", "Índice de las acciones más negociadas en la Bolsa de Valores de Colombia."),
        ("Cuenta corriente", "Balance de lo que el país vende, compra, paga y recibe del exterior."),
    ],
    "en": [
        ("GDP", "Value of everything the country produces. Its annual change measures economic growth."),
        ("Usual pace (potential GDP)", "Growth the economy can sustain without putting pressure on prices."),
        ("Output gap", "Difference between actual output and sustainable capacity, as % of that capacity."),
        ("Inflation", "Change in consumer prices over the last 12 months (DANE CPI)."),
        ("Inflation target", "Banco de la República aims for 3% inflation, with a ±1 point range."),
        ("Underlying inflation", "Inflation excluding food and regulated prices (utilities, fuels), the most volatile items."),
        ("Policy rate", "Interest rate set by Banco de la República, the benchmark for lending."),
        ("Real rate", "Interest rate net of inflation: the true cost of credit."),
        ("Neutral rate", "Real rate that neither slows nor stimulates the economy."),
        ("TES", "Colombian government bonds. UVR TES are inflation-linked."),
        ("Market-expected inflation", "Inflation implied by comparing fixed-rate and inflation-linked TES."),
        ("TRM", "Official market exchange rate: Colombian pesos per US dollar."),
        ("COLCAP", "Index of the most traded stocks on the Colombian Stock Exchange."),
        ("Current account", "Balance of what the country sells, buys, pays and receives abroad."),
    ],
}
