"""Textos del sitio en espanol e ingles: (es, en).

Regla de redaccion: frases cortas, sin jerga en la vista principal. Los terminos
tecnicos (brecha del producto, inflacion implicita, tasa neutral) solo aparecen en los
paneles "Detalle tecnico" y siempre con su explicacion.
"""

T = {
    # --- marco
    "titulo_pagina": ("ColombiaMacro · ¿Cómo va la economía colombiana?", "ColombiaMacro · How is Colombia's economy doing?"),
    "meta_desc": ("Tablero abierto con datos oficiales del DANE y el Banco de la República, actualizado a diario.",
                  "Open dashboard with official DANE and Banco de la República data, updated daily."),
    "sub_marca": ("USB Cali · datos oficiales", "USB Cali · official data"),
    "otro_idioma": ("English", "Español"),
    "nav_crec": ("Crecimiento", "Growth"), "nav_precios": ("Precios", "Prices"), "nav_banco": ("Tasas", "Rates"),
    "nav_mercados": ("Dólar y bolsa", "FX & stocks"), "nav_todos": ("Indicadores", "Indicators"),
    "kicker": ("Datos oficiales · actualización automática diaria", "Official data · updated automatically every day"),
    "datos_al": ("datos al", "data as of"),
    "generado": ("Actualizado el", "Updated on"),
    "h1": ("¿Cómo va la economía colombiana?", "How is Colombia's economy doing?"),
    "aviso_estados": ("Las etiquetas describen cada dato frente a reglas explícitas (meta de inflación, ritmo habitual de crecimiento). No son recomendaciones de inversión.",
                      "Labels describe each figure against explicit rules (inflation target, usual growth pace). They are not investment advice."),
    "horizonte": ("Ver los gráficos de los últimos", "Show charts for the last"),
    "h3": ("3 años", "3 years"), "h5": ("5 años", "5 years"), "h10": ("10 años", "10 years"), "htodo": ("Todo", "All"),
    "detalle_tecnico": ("Detalle técnico (para economistas)", "Technical detail (for economists)"),
    "aviso": ("Tablero académico con datos oficiales. No constituye recomendación de inversión.",
              "Academic dashboard built on official data. Not investment advice."),
    "pendiente": ("Pendiente de la primera descarga automática.", "Awaiting the first automated download."),

    # --- tarjetas
    "c_crec": ("Crecimiento", "Growth"), "c_inf": ("Inflación", "Inflation"), "c_tasa": ("Tasa del Banco", "Policy rate"),
    "c_empleo": ("Desempleo", "Unemployment"), "c_dolar": ("Dólar", "US dollar"), "c_bolsa": ("Bolsa (COLCAP)", "Stocks (COLCAP)"),
    "crec_detalle": ("PIB real, variación anual", "Real GDP, y/y"),
    "ritmo_normal_corto": ("Ritmo habitual", "Usual pace"),
    "inf_detalle": ("Variación anual de precios", "Annual change in prices"),
    "meta_corta": ("meta 3%", "target 3%"),
    "tasa_detalle": ("Tasa de interés de referencia", "Benchmark interest rate"),
    "empleo_detalle": ("Tasa de desempleo", "Unemployment rate"),
    "dolar_detalle": ("Pesos por dólar (TRM)", "Pesos per dollar (TRM)"),
    "bolsa_detalle": ("Índice de la Bolsa de Colombia", "Colombian stock index"),
    "hace_ano": ("Hace un año", "A year ago"), "en_un_ano": ("En un año", "Over a year"), "hoy": ("Hoy", "Today"),
    "ec_fuerte": ("Por encima de lo habitual", "Above usual pace"), "ec_normal": ("Ritmo normal", "Normal pace"),
    "ec_lento": ("Lento", "Slow"), "ec_contraccion": ("En contracción", "Contracting"),
    "ei_en_meta": ("En la meta", "On target"), "ei_baja": ("Bajo la meta", "Below target"),
    "ei_sobre_meta": ("Sobre la meta", "Above target"), "ei_alta": ("Alta", "High"),
    "ep_restrictiva": ("Alta: frena la economía", "High: slows the economy"), "ep_neutral": ("Neutral", "Neutral"),
    "ep_expansiva": ("Baja: estimula la economía", "Low: stimulates the economy"), "ep_None": ("—", "—"),
    "ep2_restrictiva": ("alto, que frena la economía para bajar la inflación", "high enough to slow the economy and bring inflation down"),
    "ep2_neutral": ("neutral, que ni frena ni estimula la economía", "neutral, neither slowing nor stimulating the economy"),
    "ep2_expansiva": ("bajo, que estimula la economía", "low, stimulating the economy"),
    "ep2_None": ("sin calificar", "not rated"),
    "el_mejora": ("Mejorando", "Improving"), "el_estable": ("Estable", "Stable"), "el_empeora": ("Empeorando", "Worsening"),
    "peso_fuerte": ("Peso más fuerte", "Stronger peso"), "peso_debil": ("Peso más débil", "Weaker peso"),
    "peso_estable": ("Estable", "Stable"),
    "sube": ("Al alza", "Rising"), "baja": ("A la baja", "Falling"), "estable": ("Estable", "Stable"),

    # --- seccion 1
    "q_crec": ("¿Está creciendo la economía?", "Is the economy growing?"),
    "resp_crec": ("La producción del país (PIB) creció {v}% en el año terminado en {q}. En los últimos años, el ritmo habitual de crecimiento de Colombia ronda el {p}%.",
                  "Output (GDP) grew {v}% in the year to {q}. In recent years, Colombia's usual growth pace has been around {p}%."),
    "resp_ise": ("El indicador mensual de actividad del DANE (ISE), sin efectos de temporada, crecía {v}% anual en {f}.",
                 "DANE's seasonally adjusted monthly activity indicator (ISE) was growing {v}% y/y in {f}."),
    "g_crec": ("Crecimiento anual de la economía", "Annual economic growth"),
    "h_crec": ("Cada barra es un trimestre: cuánto creció la economía frente al mismo trimestre del año anterior. La línea punteada es el ritmo habitual; si las barras están por encima, la economía crece más rápido de lo normal.",
               "Each bar is a quarter: growth versus the same quarter a year earlier. The dotted line is the usual pace; bars above it mean faster-than-normal growth."),
    "pib_trim": ("PIB (trimestral)", "GDP (quarterly)"), "ise_mens": ("Actividad mensual (ISE)", "Monthly activity (ISE)"),
    "ritmo_normal": ("Ritmo habitual", "Usual pace"),
    "covid_escala": ("2020–21: caída y rebote de la pandemia, fuera de escala", "2020–21: pandemic fall and rebound, off scale"),
    "g_desempleo": ("Tasa de desempleo", "Unemployment rate"),
    "h_desempleo": ("Porcentaje de personas que buscan trabajo y no lo encuentran, sin efectos de temporada. La línea azul promedia tres meses para suavizar el ruido.",
                    "Share of people looking for work who cannot find it, seasonally adjusted. The blue line is a three-month average to smooth noise."),
    "td_mensual": ("Mensual", "Monthly"), "td_3m": ("Promedio de 3 meses", "3-month average"),
    "g_brecha": ("Producción frente a su capacidad (brecha del producto)", "Output vs capacity (output gap)"),
    "h_brecha": ("Por encima de cero la economía produce más que su capacidad sostenible, lo que presiona los precios; por debajo hay holgura. La franja muestra el rango entre tres métodos de estimación.",
                 "Above zero the economy produces more than its sustainable capacity, which pushes prices up; below zero there is slack. The band shows the range across three estimation methods."),
    "rango_metodos": ("Rango entre métodos", "Range across methods"), "brecha_principal": ("Estimación principal", "Main estimate"),
    "g_reloj": ("Reloj del ciclo: en qué fase estamos", "Cycle clock: which phase we are in"),
    "h_reloj": ("Cada punto es un trimestre (el grande, el más reciente). A la derecha, la economía produce por encima de su capacidad; arriba, esa diferencia está creciendo. Fase actual: {fase}.",
                "Each dot is a quarter (the large one is the latest). Right means output above capacity; up means that difference is growing. Current phase: {fase}."),
    "brecha_eje": ("Brecha", "Gap"), "direccion_eje": ("Cambio en 2 trimestres", "Change over 2 quarters"),
    "m_brecha": ("Método: la capacidad (PIB potencial) se estima con el filtro de Hodrick-Prescott aplicado solo con la información disponible en cada trimestre (λ = 1.600), y se contrasta con el mismo filtro sobre toda la muestra y con el método de Hamilton (2018). Los trimestres de la pandemia se excluyen al estimar la tendencia. Detalle completo en la metodología.",
                 "Method: capacity (potential GDP) is estimated with a Hodrick-Prescott filter using only the data available each quarter (λ = 1,600), cross-checked with the full-sample filter and Hamilton's (2018) method. Pandemic quarters are excluded when estimating the trend. Full detail in the methodology."),

    # --- seccion 2
    "q_precios": ("¿Cómo están los precios?", "What is happening to prices?"),
    "resp_precios": ("Los precios subieron {v}% en el último año (dato de {m}); hace un año la inflación era {a}%. La meta del Banco de la República es 3%, con un margen entre 2% y 4%.",
                     "Prices rose {v}% over the past year (data for {m}); a year ago inflation was {a}%. Banco de la República's target is 3%, with a 2%–4% range."),
    "resp_basica": ("Sin alimentos ni precios regulados, que son los más volátiles, la inflación es {v}%: la presión es general.",
                    "Excluding food and regulated prices, the most volatile items, inflation is {v}%: the pressure is broad-based."),
    "resp_espera": ("Los inversionistas esperan una inflación de {v}% para el próximo año.",
                    "Investors expect inflation of {v}% over the next year."),
    "g_inf": ("Inflación anual frente a la meta", "Annual inflation vs target"),
    "h_inf": ("La franja verde es el rango meta (2% a 4%). La línea naranja quita alimentos y precios regulados para mostrar la tendencia de fondo.",
              "The green band is the target range (2%–4%). The orange line removes food and regulated prices to show the underlying trend."),
    "inf_total": ("Inflación total", "Headline inflation"), "inf_fondo": ("Inflación de fondo", "Underlying inflation"),
    "inf_observada": ("Inflación observada", "Actual inflation"), "meta_label": ("Meta 3% (rango 2%–4%)", "Target 3% (2%–4% range)"),
    "g_espera": ("¿Qué inflación espera el mercado para el próximo año?", "What inflation does the market expect next year?"),
    "h_espera": ("Se calcula con los bonos del Gobierno (TES): la diferencia entre los que pagan una tasa fija y los que se ajustan por inflación. Si la línea morada está sobre la franja, el mercado cree que la inflación seguirá alta.",
                 "Computed from government bonds (TES): the gap between fixed-rate bonds and inflation-linked bonds. If the purple line is above the band, the market expects inflation to stay high."),
    "espera_1a": ("Esperada a 1 año", "Expected, 1 year"),
    "g_anclaje": ("Inflación esperada a largo plazo (años 5 a 10)", "Long-term expected inflation (years 5 to 10)"),
    "h_anclaje": ("Si esta medida se mantiene cerca de la meta, el mercado confía en que la inflación volverá al 3%. Por encima de 4% se considera que las expectativas están desancladas.",
                  "If this stays near target, the market trusts that inflation will return to 3%. Above 4%, expectations are considered de-anchored."),
    "espera_largo": ("Esperada años 5–10 (5y5y)", "Expected years 5–10 (5y5y)"),
    "m_expect": ("Método: inflación implícita = (1 + tasa TES en pesos) / (1 + tasa TES en UVR) − 1, con curvas cero cupón de BanRep. Incluye primas por riesgo y liquidez, por lo que no es una expectativa pura.",
                 "Method: breakeven inflation = (1 + peso TES yield) / (1 + UVR TES yield) − 1, using BanRep zero-coupon curves. It includes risk and liquidity premia, so it is not a pure expectation."),

    # --- seccion 3
    "q_banco": ("¿Qué está haciendo el Banco de la República?", "What is Banco de la República doing?"),
    "resp_banco": ("La tasa de interés del Banco está en {v}%. Descontando la inflación que espera el mercado, la tasa real es {r}%, un nivel {e}.",
                   "The central bank's policy rate is {v}%. Net of market-expected inflation the real rate is {r}%, a level that is {e}."),
    "resp_banco_na": ("Pendiente de la primera descarga automática de la tasa de política.", "Awaiting the first automated download of the policy rate."),
    "g_politica": ("Tasa del Banco frente a la inflación", "Policy rate vs inflation"),
    "h_politica": ("Cuando la tasa del Banco (azul) está muy por encima de la inflación (naranja), el crédito es caro y la economía se enfría; así se busca bajar la inflación.",
                   "When the policy rate (blue) is well above inflation (orange), credit is expensive and the economy cools; that is how inflation is brought down."),
    "tpm_linea": ("Tasa del Banco de la República", "Policy rate"),
    "g_real": ("Tasa real frente a la tasa neutral", "Real rate vs neutral rate"),
    "h_real": ("La tasa neutral es la que ni frena ni estimula la economía (estimación del equipo técnico del Banco: 2,7%–3,0%). Por encima de la franja gris la política frena la economía.",
               "The neutral rate neither slows nor stimulates the economy (BanRep staff estimate: 2.7%–3.0%). Above the grey band, policy is restrictive."),
    "tasa_real": ("Tasa real ex ante", "Ex-ante real rate"), "neutral_label": ("Tasa neutral estimada 2,7%–3,0%", "Estimated neutral 2.7%–3.0%"),
    "g_curva": ("Tasas de los bonos del Gobierno por plazo (TES)", "Government bond yields by maturity (TES)"),
    "h_curva": ("Cuánto rinde prestarle al Gobierno a 1, 5 y 10 años, hoy y hace un año. Si toda la curva sube, el costo de financiarse aumenta para todos.",
                "What lending to the government pays at 1, 5 and 10 years, today and a year ago. When the whole curve rises, borrowing costs rise for everyone."),
    "hace_ano_c": ("Hace un año", "A year ago"),
    "plazo1": ("1 año", "1 year"), "plazo5": ("5 años", "5 years"), "plazo10": ("10 años", "10 years"),
    "m_politica": ("Método: tasa real ex ante = (1 + tasa del Banco) / (1 + inflación esperada a 1 año) − 1. La postura se califica como alta (restrictiva) si supera la tasa neutral estimada en más de 0,5 puntos.",
                   "Method: ex-ante real rate = (1 + policy rate) / (1 + 1-year expected inflation) − 1. The stance is called restrictive if it exceeds the estimated neutral rate by more than 0.5 points."),

    # --- seccion 4
    "q_mercados": ("¿Cómo están el dólar y la bolsa?", "How are the dollar and stocks doing?"),
    "resp_dolar": ("Un dólar cuesta ${v} pesos ({c}% en un año).", "One dollar costs ${v} pesos ({c}% over a year)."),
    "resp_bolsa": ("La bolsa colombiana (COLCAP) varió {v}% en los últimos doce meses.", "The Colombian stock index (COLCAP) moved {v}% over the last twelve months."),
    "g_dolar": ("Pesos por dólar (TRM)", "Pesos per dollar (TRM)"),
    "h_dolar": ("Si la línea baja, el peso se fortalece: se necesitan menos pesos para comprar un dólar.",
                "When the line falls the peso strengthens: fewer pesos are needed to buy one dollar."),
    "trm_linea": ("Pesos por dólar", "Pesos per dollar"),
    "g_bolsa": ("Bolsa de Colombia (COLCAP)", "Colombian stock index (COLCAP)"),
    "h_bolsa": ("Índice que resume el precio de las acciones más negociadas en Colombia. No incluye dividendos.",
                "Index summarising the prices of the most traded Colombian stocks. Excludes dividends."),
    "colcap_linea": ("COLCAP", "COLCAP"),
    "g_itcr": ("Tasa de cambio real (2010 = 100)", "Real exchange rate (2010 = 100)"),
    "h_itcr": ("Compara precios de Colombia con los de sus socios comerciales en una misma moneda. Por debajo de 100 el peso está más fuerte que en 2010.",
               "Compares Colombian prices with those of trading partners in a common currency. Below 100 the peso is stronger than in 2010."),
    "itcr_linea": ("Tasa de cambio real", "Real exchange rate"),
    "m_mercados": ("Fuentes: TRM de la Superintendencia Financiera y COLCAP (BVC/MSCI) vía BanRep. El COLCAP cambió de metodología BVC a MSCI el 28 de mayo de 2021, con continuidad de niveles.",
                   "Sources: TRM from the Financial Superintendence and COLCAP (BVC/MSCI) via BanRep. COLCAP switched from BVC to MSCI methodology on 28 May 2021, keeping level continuity."),

    # --- seccion 5
    "q_externo": ("¿Cómo están las cuentas con el exterior y del Gobierno?", "How are external and government accounts?"),
    "resp_cc": ("El país gasta en el exterior más de lo que recibe: el déficit de cuenta corriente fue de {v}% del PIB en {f}.",
                "The country spends more abroad than it earns: the current-account deficit was {v}% of GDP in {f}."),
    "resp_deuda": ("La deuda del Gobierno Nacional Central llegó a {v}% del PIB en {f}.", "Central government debt reached {v}% of GDP in {f}."),
    "g_cc": ("Cuenta corriente (% del PIB)", "Current account (% of GDP)"),
    "h_cc": ("Barras negativas: déficit, es decir, el país depende de financiación externa.",
             "Negative bars: a deficit, meaning the country relies on foreign financing."),
    "g_deuda": ("Deuda bruta del Gobierno (% del PIB)", "Central government gross debt (% of GDP)"),
    "h_deuda": ("Deuda del Gobierno Nacional Central al cierre de cada año.", "Central government debt at the end of each year."),

    # --- tablas
    "q_todos": ("Todos los indicadores", "All indicators"),
    "resp_todos": ("Cada fila muestra el último dato, cuánto cambió y si hoy está alto o bajo comparado con su propia historia desde 2010.",
                   "Each row shows the latest value, how much it changed and whether it is high or low compared with its own history since 2010."),
    "col_ind": ("Indicador", "Indicator"), "col_ult": ("Último dato", "Latest"), "col_fecha": ("Período", "Period"),
    "col_cambio": ("Cambio", "Change"), "col_hist": ("Frente a su historia", "Versus its history"),
    "en_3m": ("en 3 meses", "over 3 months"), "en_12m": ("en 12 meses", "over 12 months"),
    "niv_muy_bajo": ("Muy bajo", "Very low"), "niv_bajo": ("Bajo", "Low"), "niv_normal": ("Normal", "Normal"),
    "niv_alto": ("Alto", "High"), "niv_muy_alto": ("Muy alto", "Very high"),
    "q_fuentes": ("Fuentes y actualización", "Sources and updates"),
    "resp_fuentes": ("Todos los datos se descargan automáticamente cada día de las fuentes oficiales y pasan controles de calidad antes de publicarse.",
                     "All data are downloaded automatically every day from official sources and pass quality checks before publication."),
    "col_fuente": ("Fuente", "Source"), "col_frec": ("Frecuencia", "Frequency"), "col_ultimo": ("Último dato", "Latest"),
    "col_estado": ("Estado", "Status"),
    "fr_trimestral": ("Trimestral", "Quarterly"), "fr_mensual": ("Mensual", "Monthly"), "fr_diaria": ("Diaria", "Daily"),
    "fr_diaria_mercado": ("Diaria", "Daily"), "fr_anual": ("Anual", "Annual"),
    "st_vigente": ("Al día", "Up to date"), "st_rezagado": ("Retrasado", "Delayed"), "st_pendiente": ("Pendiente", "Pending"),
    "descargar": ("Descargar datos (CSV)", "Download data (CSV)"), "documentos": ("Documentos", "Documents"),
    "metodologia": ("Metodología", "Methodology"), "manual": ("Manual (PDF)", "Manual (PDF)"),
    "glosario": ("Glosario", "Glossary"),

    # --- cambios en los graficos
    "vs_ano": ("vs. hace 1 año", "vs. 1 year ago"), "vs_trim": ("vs. trimestre anterior", "vs. previous quarter"),
    "vs_mes": ("vs. hace 1 mes", "vs. 1 month ago"),
    "inf_mes": ("Variación del mes", "Monthly change"),
    "g_cc_corto": ("Cuenta corriente", "Current account"), "g_deuda_corto": ("Deuda del Gobierno", "Government debt"),

    # --- curva TES
    "nav_curva": ("Curva TES", "TES curve"),
    "q_curva": ("¿Cuánto cobra el mercado por prestarle al Gobierno?", "What does the market charge to lend to the government?"),
    "resp_curva": ("Al {f}, un bono del Gobierno a 1 año rinde {c}% y uno a 10 años {l}%. La diferencia entre ambos es {p} puntos: la curva está {forma}. En el último año la tasa a 10 años cambió {d} puntos. Mueva la barra de fechas para ver la curva de cualquier día desde 2003 y marque años para compararlos.",
                   "On {f}, a 1-year government bond yields {c}% and a 10-year bond {l}%. The gap is {p} points: the curve is {forma}. Over the past year the 10-year yield moved {d} points. Move the date bar to see the curve on any day since 2003 and tick years to compare them."),
    "tes_normal": ("con pendiente positiva (normal)", "upward-sloping (normal)"),
    "tes_plana": ("casi plana", "almost flat"), "tes_invertida": ("invertida (el corto plazo paga más que el largo)", "inverted (short rates above long rates)"),
    "tes_tipo": ("Tipo de bono", "Bond type"),
    "tes_pesos": ("TES en pesos (tasa nominal)", "Peso TES (nominal yield)"),
    "tes_uvr": ("TES en UVR (tasa real)", "UVR TES (real yield)"),
    "tes_fecha": ("Curva del", "Curve on"),
    "tes_volver": ("Volver al último dato", "Back to latest"),
    "tes_comparar": ("Comparar con el cierre de:", "Compare with year-end:"),
    "tes_g_curva": ("Curva cero cupón de los TES (BanRep)", "TES zero-coupon yield curve (BanRep)"),
    "tes_h_curva": ("Cada línea es una fecha: la línea azul gruesa es la fecha elegida y las demás son los años marcados. Una curva que sube de izquierda a derecha es lo normal; si baja, el mercado espera tasas menores en el futuro.",
                    "Each line is one date: the thick blue line is the selected date and the others are the ticked years. A curve rising from left to right is normal; if it falls, the market expects lower rates ahead."),
    "tes_g_hist": ("Historia de las tasas a 1, 5 y 10 años", "History of 1-, 5- and 10-year yields"),
    "tes_h_hist": ("Pase el cursor sobre la historia para ver la curva de ese día; haga clic para fijarla. La línea vertical marca la fecha elegida.",
                   "Hover over the history to see that day's curve; click to pin it. The vertical line marks the selected date."),
    "tes_pend": ("Pendiente 10 años − 1 año", "Slope 10y − 1y"),
    "m_curva": ("Método: tasas cero cupón de los TES publicadas a diario por el Banco de la República (series 15272–15277) para plazos de 1, 5 y 10 años, en pesos (nominales) y en UVR (reales). La comparación por años usa el último día hábil de cada año. El cambio se mide en puntos porcentuales frente a la observación más cercana un año antes de la fecha elegida.",
                "Method: TES zero-coupon yields published daily by Banco de la República (series 15272–15277) for 1-, 5- and 10-year tenors, in pesos (nominal) and UVR (real). Year comparisons use each year's last business day. Changes are in percentage points against the closest observation one year before the selected date."),
}

GLOSARIO = {
    "es": [
        ("PIB", "Valor de todo lo que produce el país. Su variación anual mide el crecimiento de la economía."),
        ("Ritmo habitual (PIB potencial)", "Crecimiento que la economía puede sostener sin generar presiones sobre los precios."),
        ("Brecha del producto", "Diferencia entre lo que la economía produce y su capacidad sostenible, en % de esa capacidad."),
        ("Inflación", "Variación de los precios al consumidor en los últimos 12 meses (IPC del DANE)."),
        ("Meta de inflación", "El Banco de la República busca una inflación de 3%, con un margen de ±1 punto."),
        ("Inflación de fondo", "Inflación sin alimentos ni precios regulados (servicios públicos, combustibles), que son los más volátiles."),
        ("Tasa de política", "Tasa de interés que fija el Banco de la República y que sirve de referencia para los créditos."),
        ("Tasa real", "Tasa de interés descontando la inflación. Mide cuánto cuesta realmente el crédito."),
        ("Tasa neutral", "Tasa real que ni frena ni estimula la economía."),
        ("TES", "Bonos del Gobierno colombiano. Los TES en UVR se ajustan por inflación."),
        ("Inflación esperada por el mercado", "Inflación que se deduce de comparar TES a tasa fija con TES ajustados por inflación."),
        ("TRM", "Tasa representativa del mercado: pesos colombianos por dólar."),
        ("COLCAP", "Índice de las acciones más negociadas en la Bolsa de Valores de Colombia."),
        ("Cuenta corriente", "Balance de lo que el país vende, compra, paga y recibe del exterior."),
    ],
    "en": [
        ("GDP", "Value of everything the country produces. Its annual change measures economic growth."),
        ("Usual pace (potential GDP)", "Growth the economy can sustain without putting pressure on prices."),
        ("Output gap", "Difference between actual output and sustainable capacity, as % of that capacity."),
        ("Inflation", "Change in consumer prices over the last 12 months (DANE CPI)."),
        ("Inflation target", "Banco de la República aims for 3% inflation, with a ±1 point range."),
        ("Underlying inflation", "Inflation excluding food and regulated prices (utilities, fuels), the most volatile items."),
        ("Policy rate", "Interest rate set by Banco de la República, the benchmark for lending."),
        ("Real rate", "Interest rate net of inflation: the true cost of credit."),
        ("Neutral rate", "Real rate that neither slows nor stimulates the economy."),
        ("TES", "Colombian government bonds. UVR TES are inflation-linked."),
        ("Market-expected inflation", "Inflation implied by comparing fixed-rate and inflation-linked TES."),
        ("TRM", "Official market exchange rate: Colombian pesos per US dollar."),
        ("COLCAP", "Index of the most traded stocks on the Colombian Stock Exchange."),
        ("Current account", "Balance of what the country sells, buys, pays and receives abroad."),
    ],
}
